variables:
  - template: variables.yml

stages:
- stage: Development
  jobs:
  - job: Infrastructure
    displayName: Infrastructure Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureCLI@2
      displayName: AZ CLI - Bicep Deploy
      inputs:
        azureSubscription: ${{ variables.azSubscription }}
        scriptType: 'ps'
        workingDirectory: $(Build.SourcesDirectory)\Producer
        scriptPath: $(Build.SourcesDirectory)\Producer\scripts\deploy-infra.ps1
        arguments:
          -ClientPrefix ${{ variables.clientPrefix }} `
          -Env ${{ variables.env }} `
          -AadObjectId ${{ variables.aadObjectId }}

  - job: FunctionApp
    dependsOn: Infrastructure
    condition: succeeded()
    displayName: FunctionApp Build and Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureCLI@2
      displayName: AZ CLI - Bicep Deploy
      inputs:
        azureSubscription: ${{ variables.azSubscription }}
        scriptType: 'ps'
        workingDirectory: $(Build.SourcesDirectory)\Producer
        scriptPath: $(Build.SourcesDirectory)\Producer\scripts\deploy-func.ps1
        arguments:
          -ClientPrefix ${{ variables.ClientPrefix }} `
          -Env ${{ variables.Env }}
  
  - job: APIManagement
    dependsOn: FunctionApp
    condition: succeeded()
    displayName: APIM Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureCLI@2
      displayName: AZ CLI - Bicep Deploy
      inputs:
        azureSubscription: ${{ variables.azSubscription }}
        scriptType: 'ps'
        workingDirectory: $(Build.SourcesDirectory)\Producer
        scriptPath: $(Build.SourcesDirectory)\Producer\scripts\deploy-apim.ps1
        arguments:
          -ResourceGroup ${{ variables.rg }} `
          -FunctionApp ${{ variables.func }}