CREATE PROCEDURE [STG].[usp_merge_ActivityLogs]

AS
BEGIN

	MERGE [CEN].[ActivityLogs] T
	USING [STG].[ActivityLogs] S 
	ON  T.[Id]=S.[Id]
	
	WHEN NOT MATCHED BY TARGET 
	THEN 
	INSERT ([Id]
           ,[CreationTime]
           ,[CreationTimeUTC]
           ,[RecordType]
           ,[Operation]
           ,[OrganizationId]
           ,[UserType]
           ,[UserKey]
           ,[Workload]
           ,[UserId]
           ,[ClientIP]
           ,[UserAgent]
           ,[Activity]
           ,[ItemName]
           ,[WorkSpaceName]
           ,[DashboardName]
           ,[DatasetName]
           ,[ReportName]
           ,[WorkspaceId]
           ,[ObjectId]
           ,[DashboardId]
           ,[DatasetId]
           ,[ReportId]
           ,[OrgAppPermission]
           ,[CapacityId]
           ,[CapacityName]
           ,[AppName]
           ,[IsSuccess]
           ,[ReportType]
           ,[RequestId]
           ,[ActivityId]
           ,[AppReportId]
           ,[DistributionMethod]
           ,[ConsumptionMethod]
           ,[DateRetrieved])
	VALUES ( S.[Id]
            ,S.[CreationTime]
            ,S.[CreationTimeUTC]
            ,S.[RecordType]
            ,S.[Operation]
            ,S.[OrganizationId]
            ,S.[UserType]
            ,S.[UserKey]
            ,S.[Workload]
            ,S.[UserId]
            ,S.[ClientIP]
            ,S.[UserAgent]
            ,S.[Activity]
            ,S.[ItemName]
            ,S.[WorkSpaceName]
            ,S.[DashboardName]
            ,S.[DatasetName]
            ,S.[ReportName]
            ,S.[WorkspaceId]
            ,S.[ObjectId]
            ,S.[DashboardId]
            ,S.[DatasetId]
            ,S.[ReportId]
            ,S.[OrgAppPermission]
            ,S.[CapacityId]
            ,S.[CapacityName]
            ,S.[AppName]
            ,S.[IsSuccess]
            ,S.[ReportType]
            ,S.[RequestId]
            ,S.[ActivityId]
            ,S.[AppReportId]
            ,S.[DistributionMethod]
            ,S.[ConsumptionMethod]
            ,S.[DateRetrieved]);
END

--EXEC [STG].usp_merge_ActivityLogs
