PUT http://localhost:7071/api/WorkspaceCreate?id=WACHS
content-type: application/json

{
    "workSpaceName": "new"
}
###

POST http://localhost:7071/api/WorkspaceCreate?id=WACHS
content-type: application/json

{
    "workSpaceName": "new"
}

###
https://hss-syd-dev-fun-powerbi.azurewebsites.net/api/ActivitiesScheduled?code={code}}==&clientId=apim-hss-syd-dev-api-powerbi
###

GET https://hss-syd-dev-api-powerbi.azure-api.net/hss-syd-dev-fun-powerbi/Activity
Ocp-Apim-Subscription-Key: {code}