@subscriptionKey = ???

https://hss-syd-dev-api-powerbi.azure-api.net/hss-syd-dev-fun-powerbi/Workspace?name=test
Ocp-Apim-Subscription-Key: {{subscriptionKey}}
###
https://hss-syd-dev-api-powerbi.azure-api.net/hss-syd-dev-fun-powerbi/Workspace
Ocp-Apim-Subscription-Key: {{subscriptionKey}}
content-type: application/json

{
    "workSpaceName": "new"
}
###

POST http://localhost:7071/api/WorkspaceCreate?id=wachs
content-type: application/json
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

{
    "workSpaceName": "new"
}
###

GET https://hss-syd-dev-api-powerbi.azure-api.net/hss-syd-dev-fun-powerbi/Activity
Ocp-Apim-Subscription-Key: {{subscriptionKey}}
###

GET https://hss-syd-dev-api-powerbi.azure-api.net/hss-syd-dev-fun-powerbi/WorkspaceList
Ocp-Apim-Subscription-Key: {{subscriptionKey}}