PUT http://localhost:7071/api/WorkspaceCreate?id=WACHS
content-type: application/json

{
    "workSpaceName": "new"
}
###

POST http://localhost:7071/api/WorkspaceCreate?id=WACHS
content-type: application/json

{
    "workSpaceName": "new"
}

###
GET http://localhost:7071/api/ActivitiesScheduled
