PUT http://localhost:7071/api/Workspace?id=WACHS
content-type: application/json

{
    "workSpaceName": "new"
}
###

POST http://localhost:7071/api/Workspace?id=WACHS
content-type: application/json

{
    "workSpaceName": "demo"
}
###
GET http://localhost:7071/api/Workspace?id=WACHS&name=WACHS-new

###
GET http://localhost:7071/api/Activity?id=WACHS

###
GET http://localhost:7071/api/ActivitiesScheduled
###
GET http://localhost:7071/api/WorkspacesScheduled
###
GET http://localhost:7071/api/WorkspaceList