parameters: 
  - name: data_factory_name
    type: string

jobs:
- job: 'DataFactory'
  steps:
  - bash: |
      mkdir -p "$(Build.ArtifactStagingDirectory)/adf_arm_templates"
      cp -r "${{ parameters.data_factory_name }}/." "$(Build.ArtifactStagingDirectory)/adf_arm_templates/"
    displayName: 'Prepare Azure Resource Manager template Build Artifacts'

  - publish: '$(Build.ArtifactStagingDirectory)/adf_arm_templates'
    artifact: adf_arm_templates