CREATE TABLE [STG].[ActivityLogs] (
    [Id]                                NVARCHAR (MAX) NULL,
    [CreationTime]                      NVARCHAR (MAX) NULL,
    [CreationTimeUTC]                   NVARCHAR (MAX) NULL,
    [RecordType]                        NVARCHAR (MAX) NULL,
    [Operation]                         NVARCHAR (MAX) NULL,
    [OrganizationId]                    NVARCHAR (MAX) NULL,
    [UserType]                          NVARCHAR (MAX) NULL,
    [UserKey]                           NVARCHAR (MAX) NULL,
    [Workload]                          NVARCHAR (MAX) NULL,
    [UserId]                            NVARCHAR (MAX) NULL,
    [ClientIP]                          NVARCHAR (MAX) NULL,
    [UserAgent]                         NVARCHAR (MAX) NULL,
    [Activity]                          NVARCHAR (MAX) NULL,
    [ItemName]                          NVARCHAR (MAX) NULL,
    [WorkSpaceName]                     NVARCHAR (MAX) NULL,
    [DashboardName]                     NVARCHAR (MAX) NULL,
    [DatasetName]                       NVARCHAR (MAX) NULL,
    [ReportName]                        NVARCHAR (MAX) NULL,
    [WorkspaceId]                       NVARCHAR (MAX) NULL,
    [ObjectId]                          NVARCHAR (MAX) NULL,
    [DashboardId]                       NVARCHAR (MAX) NULL,
    [DatasetId]                         NVARCHAR (MAX) NULL,
    [ReportId]                          NVARCHAR (MAX) NULL,
    [OrgAppPermission]                  NVARCHAR (MAX) NULL,
    [CapacityId]                        NVARCHAR (MAX) NULL,
    [CapacityName]                      NVARCHAR (MAX) NULL,
    [AppName]                           NVARCHAR (MAX) NULL,
    [IsSuccess]                         NVARCHAR (MAX) NULL,
    [ReportType]                        NVARCHAR (MAX) NULL,
    [RequestId]                         NVARCHAR (MAX) NULL,
    [ActivityId]                        NVARCHAR (MAX) NULL,
    [AppReportId]                       NVARCHAR (MAX) NULL,
    [DistributionMethod]                NVARCHAR (MAX) NULL,
    [ConsumptionMethod]                 NVARCHAR (MAX) NULL,
    [ExportEventStartDateTimeParameter] NVARCHAR (MAX) NULL,
    [ExportEventEndDateTimeParameter]   NVARCHAR (MAX) NULL,
    [DateRetrieved]                     NVARCHAR (MAX) NULL
);



